# Setup
title: Nabeel Zewail
url: https://
paginate: 1
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - styles.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

author:
  name: Nabeel Zewail
  url: https://github.com/nzewail
  email: nabeel@fastmail.com
